# Generated by Django 2.0.1 on 2018-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='12-12-2012', max_length=15)),
                ('name', models.CharField(blank=True, default='name', max_length=25)),
                ('greeting', models.CharField(blank=True, default='hola', max_length=25)),
            ],
        ),
    ]
